### ISSUE TITLE
Password cannot contain `%`

### ISSUE THREAD

**Issue by KPilnacek** [rossumai/elisctl#34]
When `elisctl configure` is run and a password with `%` char is entered, the following error is raised
```
Password: 
Traceback (most recent call last):
  File "/Users/krystofpilnacekrossum/workspace/tools/venv/bin/elisctl", line 11, in <module>
    load_entry_point('elis-tools', 'console_scripts', 'elisctl')()
  File "/Users/krystofpilnacekrossum/workspace/tools/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/krystofpilnacekrossum/workspace/tools/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/krystofpilnacekrossum/workspace/tools/venv/lib/python3.7/site-packages/click_shell/core.py", line 161, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "/Users/krystofpilnacekrossum/workspace/tools/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/krystofpilnacekrossum/workspace/tools/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/krystofpilnacekrossum/workspace/tools/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/krystofpilnacekrossum/workspace/tools/elisctl/configure.py", line 28, in cli
    "password": click.prompt(f"Password", hide_input=True, type=str).strip(),
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 971, in __setitem__
    self.read_dict({key: value})
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 753, in read_dict
    self.set(section, key, value)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1198, in set
    super().set(section, option, value)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 893, in set
    value)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 402, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in '"%O9#t
```

Also makes problems even when `.elis/credentials` is set manually and some API operation is carried out.

**Comment by KPilnacek** [comment]
workaround: use environment variable `ELIS_PASSWORD`
